### ISSUE TITLE
Spurious "circular dependency"

### ISSUE THREAD

**Issue by k2d222** [robtfm/naga_oil_cli#1]
Because `HashSet` is not ordered, the includes are not always visited in the right order. On my computer, it changes at each program execution.

Adding this `next_reqs.remove(req);` before the `continue;` statement below fixes this issue.
https://github.com/robtfm/naga_oil_cli/blob/66d1542e90c44a28d6825879a968fdb34b437a0d/src/main.rs#L219

**Comment by robtfm** [comment]
Could you give an example that shows the problem please?

**Comment by k2d222** [comment]
ofc, here's a minimal setup to reproduce.

`shader1.wgsl`:
```wgsl
#import "shader2.wgsl"::f2;

@vertex
fn f1() -> vec4f {
    return f2();
}
```

`shader2.wgsl`:
```wgsl
#import "shader3.wgsl"::f3;

fn f2() -> vec4f {
    return f3();
}
```

`shader3.wgsl`:
```wgsl
fn f3() -> vec4f {
    return vec4f();
}
```

run `naga_oil_cli shader1.wgsl`

possible output 1:

```
found "shader2.wgsl"
found "shader1.wgsl"
found "shader3.wgsl"
adding module "shader3.wgsl"
adding module "shader2.wgsl"
fn f3X_naga_oil_mod_XEJZWQYLEMVZDGLTXM5ZWYIQX() -> vec4<f32> {
    return vec4<f32>();
}

fn f2X_naga_oil_mod_XEJZWQYLEMVZDELTXM5ZWYIQX() -> vec4<f32> {
    let _e0: vec4<f32> = f3X_naga_oil_mod_XEJZWQYLEMVZDGLTXM5ZWYIQX();
    return _e0;
}

@vertex 
fn f1_() -> vec4<f32> {
    let _e0: vec4<f32> = f2X_naga_oil_mod_XEJZWQYLEMVZDELTXM5ZWYIQX();
    return _e0;
}
```

possible output 2:

```
found "shader2.wgsl"
found "shader1.wgsl"
found "shader3.wgsl"
adding module "shader3.wgsl"
thread 'main' panicked at src/main.rs:235:13:
circular dependency: {"\"shader3.wgsl\"", "\"shader2.wgsl\""}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On my computer, ouput 1 or 2 happen at random with a 50% chance for each execution. I found that the cause is the order of iter() of the HashSet [here](https://github.com/robtfm/naga_oil_cli/blob/66d1542e90c44a28d6825879a968fdb34b437a0d/src/main.rs#L202). I could confirm that by adding that before:
```rs
print!("reqs: ");
for r in reqs.iter() {
    print!("{r} ")
}
println!("");
```

which prints
```
reqs: "shader2.wgsl" 
reqs: "shader3.wgsl" "shader2.wgsl"
```
for output 1 and 
```
reqs: "shader2.wgsl" 
reqs: "shader2.wgsl" "shader3.wgsl" 
```
for output 2. In other words, the iteration order is not always the insertion order.

**Comment by robtfm** [comment]
thanks, i added your fix.
